"""add bookclub ratings

Revision ID: 18ff706897d1
Revises: c0120c3eb653
Create Date: 2026-08-08 17:48:46.858829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18ff706897d1'
down_revision: Union[str, None] = 'c0120c3eb653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookclub_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_bookclub_rating_range'),
    sa.ForeignKeyConstraint(['book_id'], ['bookclub_books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['club_id'], ['book_clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['bookclub_participant_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'participant_id', name='uq_bookclub_rating_book_participant')
    )
    op.create_index(op.f('ix_bookclub_ratings_book_id'), 'bookclub_ratings', ['book_id'], unique=False)
    op.create_index(op.f('ix_bookclub_ratings_club_id'), 'bookclub_ratings', ['club_id'], unique=False)
    op.create_index(op.f('ix_bookclub_ratings_participant_id'), 'bookclub_ratings', ['participant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookclub_ratings_participant_id'), table_name='bookclub_ratings')
    op.drop_index(op.f('ix_bookclub_ratings_club_id'), table_name='bookclub_ratings')
    op.drop_index(op.f('ix_bookclub_ratings_book_id'), table_name='bookclub_ratings')
    op.drop_table('bookclub_ratings')
    # ### end Alembic commands ###
