"""add bookclub registrant, reminder, and video-link tracking

Revision ID: 1b6da15978d9
Revises: c402f8681d7a
Create Date: 2026-08-04 23:05:18.794372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b6da15978d9'
down_revision: Union[str, None] = 'c402f8681d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_clubs', sa.Column('video_call_url', sa.String(length=500), nullable=True))
    op.add_column('bookclub_meetings', sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookclub_members', sa.Column('is_new_registrant', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('bookclub_members', sa.Column('onboarding_email_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookclub_members', sa.Column('last_reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookclub_members', 'last_reminder_sent_at')
    op.drop_column('bookclub_members', 'onboarding_email_sent_at')
    op.drop_column('bookclub_members', 'is_new_registrant')
    op.drop_column('bookclub_meetings', 'reminder_sent_at')
    op.drop_column('book_clubs', 'video_call_url')
    # ### end Alembic commands ###
