"""add bookclub date polling

Revision ID: 3118e6bbdbc9
Revises: 6825cf853e8f
Create Date: 2026-08-08 18:22:20.613259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3118e6bbdbc9'
down_revision: Union[str, None] = '6825cf853e8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookclub_date_polls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('winning_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['book_clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookclub_date_polls_club_id'), 'bookclub_date_polls', ['club_id'], unique=False)
    op.create_table('bookclub_date_poll_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('option_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['bookclub_date_polls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'option_date', name='uq_bookclub_date_poll_option')
    )
    op.create_index(op.f('ix_bookclub_date_poll_options_poll_id'), 'bookclub_date_poll_options', ['poll_id'], unique=False)
    op.create_table('bookclub_date_poll_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['bookclub_date_poll_options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['bookclub_participant_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poll_id'], ['bookclub_date_polls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'participant_id', name='uq_bookclub_date_poll_vote')
    )
    op.create_index(op.f('ix_bookclub_date_poll_votes_option_id'), 'bookclub_date_poll_votes', ['option_id'], unique=False)
    op.create_index(op.f('ix_bookclub_date_poll_votes_participant_id'), 'bookclub_date_poll_votes', ['participant_id'], unique=False)
    op.create_index(op.f('ix_bookclub_date_poll_votes_poll_id'), 'bookclub_date_poll_votes', ['poll_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookclub_date_poll_votes_poll_id'), table_name='bookclub_date_poll_votes')
    op.drop_index(op.f('ix_bookclub_date_poll_votes_participant_id'), table_name='bookclub_date_poll_votes')
    op.drop_index(op.f('ix_bookclub_date_poll_votes_option_id'), table_name='bookclub_date_poll_votes')
    op.drop_table('bookclub_date_poll_votes')
    op.drop_index(op.f('ix_bookclub_date_poll_options_poll_id'), table_name='bookclub_date_poll_options')
    op.drop_table('bookclub_date_poll_options')
    op.drop_index(op.f('ix_bookclub_date_polls_club_id'), table_name='bookclub_date_polls')
    op.drop_table('bookclub_date_polls')
    # ### end Alembic commands ###
