"""move delivery choice to member, drop redundant participation fields

Revision ID: 4203e29da79c
Revises: 1b6da15978d9
Create Date: 2026-08-05 00:48:49.153589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4203e29da79c'
down_revision: Union[str, None] = '1b6da15978d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookclub_members', sa.Column('delivery_method', sa.String(length=30), server_default='none', nullable=False))
    op.add_column('bookclub_members', sa.Column('destination_branch', sa.String(length=200), nullable=True))
    op.add_column('bookclub_members', sa.Column('arrival_email_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    # Backfill each member's delivery choice from their most recent
    # non-"none" participation row, before those columns are dropped below.
    op.execute(
        """
        UPDATE bookclub_members SET
          delivery_method = (
            SELECT delivery_method FROM bookclub_participation
            WHERE member_id = bookclub_members.id AND delivery_method != 'none'
            ORDER BY id DESC LIMIT 1
          ),
          destination_branch = (
            SELECT destination_branch FROM bookclub_participation
            WHERE member_id = bookclub_members.id AND delivery_method != 'none'
            ORDER BY id DESC LIMIT 1
          )
        WHERE EXISTS (
          SELECT 1 FROM bookclub_participation
          WHERE member_id = bookclub_members.id AND delivery_method != 'none'
        )
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookclub_participation', 'delivery_method')
    op.drop_column('bookclub_participation', 'book_checked_out')
    op.drop_column('bookclub_participation', 'destination_branch')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookclub_participation', sa.Column('destination_branch', sa.VARCHAR(length=200), nullable=True))
    op.add_column('bookclub_participation', sa.Column('book_checked_out', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))
    op.add_column('bookclub_participation', sa.Column('delivery_method', sa.VARCHAR(length=30), server_default=sa.text("'none'"), nullable=False))
    op.drop_column('bookclub_members', 'arrival_email_sent_at')
    op.drop_column('bookclub_members', 'destination_branch')
    op.drop_column('bookclub_members', 'delivery_method')
    # ### end Alembic commands ###
