"""add bookclub voting

Revision ID: 6825cf853e8f
Revises: 18ff706897d1
Create Date: 2026-08-08 18:03:36.214814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6825cf853e8f'
down_revision: Union[str, None] = '18ff706897d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookclub_voting_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('winning_book_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['book_clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winning_book_id'], ['bookclub_books.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookclub_voting_rounds_club_id'), 'bookclub_voting_rounds', ['club_id'], unique=False)
    op.create_table('bookclub_book_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voting_round_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('proposed_by_participant_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['bookclub_books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposed_by_participant_id'], ['bookclub_participant_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voting_round_id'], ['bookclub_voting_rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voting_round_id', 'book_id', name='uq_bookclub_candidate_round_book')
    )
    op.create_index(op.f('ix_bookclub_book_candidates_book_id'), 'bookclub_book_candidates', ['book_id'], unique=False)
    op.create_index(op.f('ix_bookclub_book_candidates_voting_round_id'), 'bookclub_book_candidates', ['voting_round_id'], unique=False)
    op.create_table('bookclub_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voting_round_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['bookclub_book_candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['bookclub_participant_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voting_round_id'], ['bookclub_voting_rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voting_round_id', 'participant_id', name='uq_bookclub_vote_round_participant')
    )
    op.create_index(op.f('ix_bookclub_votes_candidate_id'), 'bookclub_votes', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_bookclub_votes_participant_id'), 'bookclub_votes', ['participant_id'], unique=False)
    op.create_index(op.f('ix_bookclub_votes_voting_round_id'), 'bookclub_votes', ['voting_round_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookclub_votes_voting_round_id'), table_name='bookclub_votes')
    op.drop_index(op.f('ix_bookclub_votes_participant_id'), table_name='bookclub_votes')
    op.drop_index(op.f('ix_bookclub_votes_candidate_id'), table_name='bookclub_votes')
    op.drop_table('bookclub_votes')
    op.drop_index(op.f('ix_bookclub_book_candidates_voting_round_id'), table_name='bookclub_book_candidates')
    op.drop_index(op.f('ix_bookclub_book_candidates_book_id'), table_name='bookclub_book_candidates')
    op.drop_table('bookclub_book_candidates')
    op.drop_index(op.f('ix_bookclub_voting_rounds_club_id'), table_name='bookclub_voting_rounds')
    op.drop_table('bookclub_voting_rounds')
    # ### end Alembic commands ###
