"""add checkin card missing flag to lendery items

Revision ID: a4af3deaaa80
Revises: 4203e29da79c
Create Date: 2026-08-05 18:15:03.740330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4af3deaaa80'
down_revision: Union[str, None] = '4203e29da79c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lendery_items', sa.Column('checkin_card_missing', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lendery_items', 'checkin_card_missing')
    # ### end Alembic commands ###
