"""add participant role and club type

Revision ID: c0120c3eb653
Revises: f3c53989d79e
Create Date: 2026-08-08 14:42:15.891840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0120c3eb653'
down_revision: Union[str, None] = 'f3c53989d79e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_clubs', sa.Column('club_type', sa.String(length=20), server_default='library', nullable=False))
    op.add_column('bookclub_participant_accounts', sa.Column('role', sa.String(length=20), server_default='member', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookclub_participant_accounts', 'role')
    op.drop_column('book_clubs', 'club_type')
    # ### end Alembic commands ###
