"""baseline schema

Revision ID: c402f8681d7a
Revises: 
Create Date: 2026-08-04 11:28:08.304313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c402f8681d7a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('public', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('organizer_name', sa.String(length=200), nullable=True),
    sa.Column('organizer_branch', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_clubs_slug'), 'book_clubs', ['slug'], unique=True)
    op.create_table('lendery_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchase_url', sa.String(length=500), nullable=True),
    sa.Column('manual_url', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('library_url', sa.String(length=500), nullable=True),
    sa.Column('availability_status', sa.String(length=20), server_default='unknown', nullable=False),
    sa.Column('availability_status_version', sa.Integer(), server_default='2', nullable=False),
    sa.Column('available_copies', sa.Integer(), nullable=True),
    sa.Column('total_copies_at_branch', sa.Integer(), nullable=True),
    sa.Column('availability_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('availability_error', sa.Text(), nullable=True),
    sa.Column('physical_manual_included', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('physical_manual_missing', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('lifecycle_status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('lifecycle_note', sa.Text(), nullable=True),
    sa.Column('lifecycle_changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    op.create_index(op.f('ix_lendery_items_lifecycle_status'), 'lendery_items', ['lifecycle_status'], unique=False)
    op.create_table('libtools_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('recovery_code_hash', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='user', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('session_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('quick_actions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_libtools_users_email'), 'libtools_users', ['email'], unique=True)
    op.create_index(op.f('ix_libtools_users_username'), 'libtools_users', ['username'], unique=True)
    op.create_table('book_club_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='owner', nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['book_clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['libtools_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'user_id', name='uq_book_club_user')
    )
    op.create_index(op.f('ix_book_club_access_club_id'), 'book_club_access', ['club_id'], unique=False)
    op.create_index(op.f('ix_book_club_access_user_id'), 'book_club_access', ['user_id'], unique=False)
    op.create_table('bookclub_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('genres', sa.String(length=500), nullable=True),
    sa.Column('series', sa.String(length=300), nullable=True),
    sa.Column('catalogue_url', sa.String(length=500), nullable=True),
    sa.Column('discussion_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['book_clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'isbn', name='uq_bookclub_club_isbn')
    )
    op.create_index(op.f('ix_bookclub_books_author'), 'bookclub_books', ['author'], unique=False)
    op.create_index(op.f('ix_bookclub_books_club_id'), 'bookclub_books', ['club_id'], unique=False)
    op.create_index(op.f('ix_bookclub_books_isbn'), 'bookclub_books', ['isbn'], unique=False)
    op.create_index(op.f('ix_bookclub_books_title'), 'bookclub_books', ['title'], unique=False)
    op.create_table('bookclub_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('joined_on', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['book_clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'email', name='uq_bookclub_club_email')
    )
    op.create_index(op.f('ix_bookclub_members_club_id'), 'bookclub_members', ['club_id'], unique=False)
    op.create_index(op.f('ix_bookclub_members_email'), 'bookclub_members', ['email'], unique=False)
    op.create_table('bookclub_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['book_clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'key', name='uq_bookclub_club_template_key')
    )
    op.create_index(op.f('ix_bookclub_templates_club_id'), 'bookclub_templates', ['club_id'], unique=False)
    op.create_index(op.f('ix_bookclub_templates_key'), 'bookclub_templates', ['key'], unique=False)
    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('optional', sa.Boolean(), nullable=False),
    sa.Column('check_in_notes', sa.Text(), nullable=True),
    sa.Column('missing_reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('missing_reported_by', sa.String(length=80), nullable=True),
    sa.Column('missing_note', sa.Text(), nullable=True),
    sa.Column('missing_ignored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('missing_ignored_by', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['lendery_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lendery_item_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_item_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('item_barcode', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('item_category', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('component_name', sa.String(length=200), nullable=True),
    sa.Column('maintenance_case_id', sa.Integer(), nullable=True),
    sa.Column('part_name', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vendor_url', sa.String(length=500), nullable=True),
    sa.Column('order_number', sa.String(length=100), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(length=200), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['lendery_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_id', name='uq_lendery_item_activity_source')
    )
    op.create_index(op.f('ix_lendery_item_activity_event_type'), 'lendery_item_activity', ['event_type'], unique=False)
    op.create_index(op.f('ix_lendery_item_activity_item_category'), 'lendery_item_activity', ['item_category'], unique=False)
    op.create_index(op.f('ix_lendery_item_activity_item_id'), 'lendery_item_activity', ['item_id'], unique=False)
    op.create_index(op.f('ix_lendery_item_activity_maintenance_case_id'), 'lendery_item_activity', ['maintenance_case_id'], unique=False)
    op.create_index(op.f('ix_lendery_item_activity_occurred_at'), 'lendery_item_activity', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_lendery_item_activity_original_item_id'), 'lendery_item_activity', ['original_item_id'], unique=False)
    op.create_table('lendery_item_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('product_url', sa.String(length=500), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_name', sa.String(length=200), nullable=False),
    sa.Column('submission_key', sa.String(length=64), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['libtools_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submitted_by_user_id', 'submission_key', name='uq_lendery_suggestion_submission')
    )
    op.create_index(op.f('ix_lendery_item_suggestions_submitted_at'), 'lendery_item_suggestions', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_lendery_item_suggestions_submitted_by_user_id'), 'lendery_item_suggestions', ['submitted_by_user_id'], unique=False)
    op.create_table('libtools_account_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['libtools_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_libtools_account_tokens_expires_at'), 'libtools_account_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_libtools_account_tokens_purpose'), 'libtools_account_tokens', ['purpose'], unique=False)
    op.create_index(op.f('ix_libtools_account_tokens_token_hash'), 'libtools_account_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_libtools_account_tokens_user_id'), 'libtools_account_tokens', ['user_id'], unique=False)
    op.create_table('libtools_tool_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tool_key', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['libtools_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tool_key', name='uq_libtools_user_tool')
    )
    op.create_index(op.f('ix_libtools_tool_access_tool_key'), 'libtools_tool_access', ['tool_key'], unique=False)
    op.create_index(op.f('ix_libtools_tool_access_user_id'), 'libtools_tool_access', ['user_id'], unique=False)
    op.create_table('bookclub_meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('meeting_time', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('book_title', sa.String(length=300), nullable=False),
    sa.Column('book_author', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('giveaway_winner_member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['bookclub_books.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['club_id'], ['book_clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['giveaway_winner_member_id'], ['bookclub_members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookclub_meetings_book_id'), 'bookclub_meetings', ['book_id'], unique=False)
    op.create_index(op.f('ix_bookclub_meetings_club_id'), 'bookclub_meetings', ['club_id'], unique=False)
    op.create_index(op.f('ix_bookclub_meetings_meeting_date'), 'bookclub_meetings', ['meeting_date'], unique=False)
    op.create_table('lendery_maintenance_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('component_name', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='open', nullable=False),
    sa.Column('opened_by_user_id', sa.Integer(), nullable=False),
    sa.Column('opened_by_name', sa.String(length=80), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['lendery_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opened_by_user_id'], ['libtools_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lendery_maintenance_cases_component_id'), 'lendery_maintenance_cases', ['component_id'], unique=False)
    op.create_index(op.f('ix_lendery_maintenance_cases_item_id'), 'lendery_maintenance_cases', ['item_id'], unique=False)
    op.create_index(op.f('ix_lendery_maintenance_cases_opened_by_user_id'), 'lendery_maintenance_cases', ['opened_by_user_id'], unique=False)
    op.create_index(op.f('ix_lendery_maintenance_cases_status'), 'lendery_maintenance_cases', ['status'], unique=False)
    op.create_table('bookclub_discussion_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['bookclub_meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'position', name='uq_bookclub_question_position')
    )
    op.create_index(op.f('ix_bookclub_discussion_questions_meeting_id'), 'bookclub_discussion_questions', ['meeting_id'], unique=False)
    op.create_table('bookclub_participation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('delivery_method', sa.String(length=30), server_default='none', nullable=False),
    sa.Column('destination_branch', sa.String(length=200), nullable=True),
    sa.Column('book_checked_out', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('attended', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['bookclub_meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['bookclub_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'member_id', name='uq_bookclub_meeting_member')
    )
    op.create_index(op.f('ix_bookclub_participation_meeting_id'), 'bookclub_participation', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_bookclub_participation_member_id'), 'bookclub_participation', ['member_id'], unique=False)
    op.create_table('lendery_maintenance_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('part_name', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vendor_url', sa.String(length=500), nullable=True),
    sa.Column('order_number', sa.String(length=100), nullable=True),
    sa.Column('status_after', sa.String(length=30), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_by_name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['lendery_maintenance_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['libtools_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lendery_maintenance_events_case_id'), 'lendery_maintenance_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_lendery_maintenance_events_created_by_user_id'), 'lendery_maintenance_events', ['created_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lendery_maintenance_events_created_by_user_id'), table_name='lendery_maintenance_events')
    op.drop_index(op.f('ix_lendery_maintenance_events_case_id'), table_name='lendery_maintenance_events')
    op.drop_table('lendery_maintenance_events')
    op.drop_index(op.f('ix_bookclub_participation_member_id'), table_name='bookclub_participation')
    op.drop_index(op.f('ix_bookclub_participation_meeting_id'), table_name='bookclub_participation')
    op.drop_table('bookclub_participation')
    op.drop_index(op.f('ix_bookclub_discussion_questions_meeting_id'), table_name='bookclub_discussion_questions')
    op.drop_table('bookclub_discussion_questions')
    op.drop_index(op.f('ix_lendery_maintenance_cases_status'), table_name='lendery_maintenance_cases')
    op.drop_index(op.f('ix_lendery_maintenance_cases_opened_by_user_id'), table_name='lendery_maintenance_cases')
    op.drop_index(op.f('ix_lendery_maintenance_cases_item_id'), table_name='lendery_maintenance_cases')
    op.drop_index(op.f('ix_lendery_maintenance_cases_component_id'), table_name='lendery_maintenance_cases')
    op.drop_table('lendery_maintenance_cases')
    op.drop_index(op.f('ix_bookclub_meetings_meeting_date'), table_name='bookclub_meetings')
    op.drop_index(op.f('ix_bookclub_meetings_club_id'), table_name='bookclub_meetings')
    op.drop_index(op.f('ix_bookclub_meetings_book_id'), table_name='bookclub_meetings')
    op.drop_table('bookclub_meetings')
    op.drop_index(op.f('ix_libtools_tool_access_user_id'), table_name='libtools_tool_access')
    op.drop_index(op.f('ix_libtools_tool_access_tool_key'), table_name='libtools_tool_access')
    op.drop_table('libtools_tool_access')
    op.drop_index(op.f('ix_libtools_account_tokens_user_id'), table_name='libtools_account_tokens')
    op.drop_index(op.f('ix_libtools_account_tokens_token_hash'), table_name='libtools_account_tokens')
    op.drop_index(op.f('ix_libtools_account_tokens_purpose'), table_name='libtools_account_tokens')
    op.drop_index(op.f('ix_libtools_account_tokens_expires_at'), table_name='libtools_account_tokens')
    op.drop_table('libtools_account_tokens')
    op.drop_index(op.f('ix_lendery_item_suggestions_submitted_by_user_id'), table_name='lendery_item_suggestions')
    op.drop_index(op.f('ix_lendery_item_suggestions_submitted_at'), table_name='lendery_item_suggestions')
    op.drop_table('lendery_item_suggestions')
    op.drop_index(op.f('ix_lendery_item_activity_original_item_id'), table_name='lendery_item_activity')
    op.drop_index(op.f('ix_lendery_item_activity_occurred_at'), table_name='lendery_item_activity')
    op.drop_index(op.f('ix_lendery_item_activity_maintenance_case_id'), table_name='lendery_item_activity')
    op.drop_index(op.f('ix_lendery_item_activity_item_id'), table_name='lendery_item_activity')
    op.drop_index(op.f('ix_lendery_item_activity_item_category'), table_name='lendery_item_activity')
    op.drop_index(op.f('ix_lendery_item_activity_event_type'), table_name='lendery_item_activity')
    op.drop_table('lendery_item_activity')
    op.drop_table('components')
    op.drop_index(op.f('ix_bookclub_templates_key'), table_name='bookclub_templates')
    op.drop_index(op.f('ix_bookclub_templates_club_id'), table_name='bookclub_templates')
    op.drop_table('bookclub_templates')
    op.drop_index(op.f('ix_bookclub_members_email'), table_name='bookclub_members')
    op.drop_index(op.f('ix_bookclub_members_club_id'), table_name='bookclub_members')
    op.drop_table('bookclub_members')
    op.drop_index(op.f('ix_bookclub_books_title'), table_name='bookclub_books')
    op.drop_index(op.f('ix_bookclub_books_isbn'), table_name='bookclub_books')
    op.drop_index(op.f('ix_bookclub_books_club_id'), table_name='bookclub_books')
    op.drop_index(op.f('ix_bookclub_books_author'), table_name='bookclub_books')
    op.drop_table('bookclub_books')
    op.drop_index(op.f('ix_book_club_access_user_id'), table_name='book_club_access')
    op.drop_index(op.f('ix_book_club_access_club_id'), table_name='book_club_access')
    op.drop_table('book_club_access')
    op.drop_index(op.f('ix_libtools_users_username'), table_name='libtools_users')
    op.drop_index(op.f('ix_libtools_users_email'), table_name='libtools_users')
    op.drop_table('libtools_users')
    op.drop_index(op.f('ix_lendery_items_lifecycle_status'), table_name='lendery_items')
    op.drop_table('lendery_items')
    op.drop_index(op.f('ix_book_clubs_slug'), table_name='book_clubs')
    op.drop_table('book_clubs')
    # ### end Alembic commands ###
