"""add participant unsubscribed_at

Revision ID: c445e16b6173
Revises: 3118e6bbdbc9
Create Date: 2026-08-08 18:41:38.339867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c445e16b6173'
down_revision: Union[str, None] = '3118e6bbdbc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookclub_participant_accounts', sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookclub_participant_accounts', 'unsubscribed_at')
    # ### end Alembic commands ###
