"""add meeting duration and archive fields

Revision ID: f06fece22726
Revises: e93f1a6b2c47
Create Date: 2026-08-06 01:50:48.274539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f06fece22726'
down_revision: Union[str, None] = 'e93f1a6b2c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookclub_meetings', sa.Column('meeting_duration_minutes', sa.Integer(), server_default='90', nullable=False))
    op.add_column('bookclub_meetings', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    # "cancelled" and "in_progress" are no longer valid persisted status
    # values — cancelled meetings are deleted instead, and in-progress is
    # now computed from meeting time + duration rather than stored. Any
    # existing rows with those values are re-labeled to the safe default
    # rather than deleted, so no meeting data is lost.
    op.execute(
        "UPDATE bookclub_meetings SET status = 'planned' "
        "WHERE status NOT IN ('planned', 'completed')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookclub_meetings', 'archived_at')
    op.drop_column('bookclub_meetings', 'meeting_duration_minutes')
    # ### end Alembic commands ###
