"""add bookclub participant accounts

Revision ID: f3c53989d79e
Revises: f06fece22726
Create Date: 2026-08-08 13:28:26.709343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c53989d79e'
down_revision: Union[str, None] = 'f06fece22726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookclub_participant_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['book_clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'email', name='uq_bookclub_participant_club_email')
    )
    op.create_index(op.f('ix_bookclub_participant_accounts_club_id'), 'bookclub_participant_accounts', ['club_id'], unique=False)
    op.create_index(op.f('ix_bookclub_participant_accounts_email'), 'bookclub_participant_accounts', ['email'], unique=False)
    op.create_table('bookclub_participant_account_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['bookclub_participant_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookclub_participant_account_tokens_expires_at'), 'bookclub_participant_account_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_bookclub_participant_account_tokens_participant_id'), 'bookclub_participant_account_tokens', ['participant_id'], unique=False)
    op.create_index(op.f('ix_bookclub_participant_account_tokens_purpose'), 'bookclub_participant_account_tokens', ['purpose'], unique=False)
    op.create_index(op.f('ix_bookclub_participant_account_tokens_token_hash'), 'bookclub_participant_account_tokens', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookclub_participant_account_tokens_token_hash'), table_name='bookclub_participant_account_tokens')
    op.drop_index(op.f('ix_bookclub_participant_account_tokens_purpose'), table_name='bookclub_participant_account_tokens')
    op.drop_index(op.f('ix_bookclub_participant_account_tokens_participant_id'), table_name='bookclub_participant_account_tokens')
    op.drop_index(op.f('ix_bookclub_participant_account_tokens_expires_at'), table_name='bookclub_participant_account_tokens')
    op.drop_table('bookclub_participant_account_tokens')
    op.drop_index(op.f('ix_bookclub_participant_accounts_email'), table_name='bookclub_participant_accounts')
    op.drop_index(op.f('ix_bookclub_participant_accounts_club_id'), table_name='bookclub_participant_accounts')
    op.drop_table('bookclub_participant_accounts')
    # ### end Alembic commands ###
